import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button, TextInput, PasswordInput } from '@mantine/core';
import { useForm } from '@mantine/form';

const Home: NextPage = () => {
    const form = useForm({
        initialValues: { username: '', password: '' },

        validate: {
            username: (value) => (value.length < 2 ? 'Username must have at least 2 letters' : null),
            password: (value) => (value.length < 2 ? 'Password must have at least 2 letters' : null),
        },
    });

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <form onSubmit={form.onSubmit(console.log)}>
                    <TextInput
                        placeholder="Input your username"
                        label="Username"
                        required
                        {...form.getInputProps('username')}
                    />
                    <PasswordInput
                        placeholder="Input your password"
                        label="Password"
                        required
                        {...form.getInputProps('password')}
                    />

                    <Button type="submit" mt="sm">
                        Login
                    </Button>
                </form>
            </main>

        </div>
    );
};

export default Home;
